project_id = "sfwxbotcnfpjkwrsfyqj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54328
site_url = "https://organizese.chromotech.com.br"
additional_redirect_urls = ["https://organizese.chromotech.com.br"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_email_change_enabled = true
secure_password_change_enabled = true

[auth.sms]
enable_signup = false
enable_confirmations = false

[edge_functions]
enabled = true
port = 54329
inspector_port = 54330

[functions.send-auth-emails]
verify_jwt = false

[functions.export-database]
verify_jwt = true

[functions.export-to-excel]
verify_jwt = true

[functions.send-team-invitation]
verify_jwt = true

[functions.accept-team-invitation]
verify_jwt = true

# Webhook configuration for auth emails
[auth.hook.send_sms]
enabled = false

[auth.hook.send_email]
enabled = true
uri = "https://sfwxbotcnfpjkwrsfyqj.supabase.co/functions/v1/send-auth-emails"